version: 2

project_name: terraform-provider-template
builds:
  - main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: "-s -w"
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    args: null

release:
  github:
    owner: gmllt
    name: terraform-provider-template

changelog:
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
